steps:
  # Terraform Init
  - name: 'hashicorp/terraform:light'
    args: ['init']
    dir: 'terraform'
    id: 'tf-init'
    env:
      - 'TF_WORKSPACE=dev'

  # Terraform Plan
  - name: 'hashicorp/terraform:light'
    args: 
      - 'plan'
      - '-var-file=dev.tfvars'
      - '-var'
      - 'image_tag=$COMMIT_SHA'
    dir: 'terraform'
    id: 'tf-plan'
    env:
      - 'TF_WORKSPACE=dev'

substitutions:
  _REGION: 'us-central1'

options:
  logging: CLOUD_LOGGING_ONLY
