steps:
  # Terraform Init
  - name: 'hashicorp/terraform:light'
    args: ['init']
    dir: 'terraform'
    id: 'tf-init'
    env:
      - 'TF_WORKSPACE=prod'

  # Terraform Plan
  - name: 'hashicorp/terraform:light'
    args: 
      - 'plan'
      - '-var'
      - 'region=$_REGION'
      - '-var'
      - 'service_name=$_SERVICE_NAME'
      - '-var'
      - 'github_owner=$_GITHUB_OWNER'
      - '-var'
      - 'github_repo=$_GITHUB_REPO'
      - '-var'
      - 'image_tag=$COMMIT_SHA'
    dir: 'terraform'
    id: 'tf-plan'
    env:
      - 'TF_WORKSPACE=prod'

substitutions:
  _REGION: 'us-central1'
  _SERVICE_NAME: 'python-cloudrun-app'
  # GitHub variables passed by the trigger
  _GITHUB_OWNER: 'billnapier' 
  _GITHUB_REPO: 'calendarsync'

options:
  logging: CLOUD_LOGGING_ONLY
